### ISSUE TITLE
Error setting up environment to start Jupyter notebooks

### ISSUE THREAD

**Issue by ValentinLouis** [niklastoe/classifier_metric_uncertainty#1]
Hello,

I hope this is still an active repository. I am trying to test the classifier uncertainty tool that I found in your paper from 2020. I am trying to install the libraries from the requirements.txt file but I am encountering several problems with the library version. Errors I encounter are first the notebook doesn't work and I need to install a library called nbconvert. Then the the libraries called within the import call from __init__ import ConfusionMatrixAnalyser through multiple issues. Some are IMportErrors related to DLLs.

Do you have any advise on how best to set the environment up to test the tool/functions?

I have it tested using Python 3.7.

Thanks.

**Comment by niklastoe** [comment]
I'm not actively developing the repository but I'm happy to help you get it up and running. In order to help you, could you please provide the following information?

1.  Which problems do you face when you run `pip install -r requirements.txt`? I just repeated this, for me there were no errors using python 3.7.12 and pip 23.0.1 
2. Could you please attach the stack trace or a screenshot of the problems you face when you try to access the jupyter notebook?
3. Please paste the errors when importing from `__init__`.
4. Which DLLs are causing the problems? I assume this has more to do with your local setup. Which operating system are you using? You might have to download these individually and define the proper dll path.

I could create a new environment, install the requirements and run the notebook without any of the issues you mentioned. It appears to me that the interactive parts in the notebook, which are only for the users convenience and not necessary, do not work with the version of ipywidgets I installed (unfortunately, it is not defined in requirements.txt).

**Comment by ValentinLouis** [comment]
Hi Niklas,

I have managed to sort out the problem by adding the environment variables temproally to the system using these lines of code:

import os

# environemnt variables required to fix DLL issue - lines below temporarily edd the environment variables
base_path = r"C:/path/to/miniconda3/envs/uncertain_env/"
path = os.pathsep.join([os.path.join(base_path, i) for i in [r"", r"bin", r"Scripts", r"Library\mingw-w64\bin", r"Library\bin"]])
os.environ["PATH"]+=os.pathsep+path

That sorted it for me.

Thanks again for your offer to help setting it up.

All the best,
Valentin

**Comment by niklastoe** [comment]
That's great! I'll close the issue, feel free to open up a new one in case you have other questions about the implementation or the science.
